name:  Publish documentation 

on:
  repository_dispatch:
    types: ["publish"]
  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: main
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: hspec/hspec
          ref: ${{ inputs.ref || 'main' }}
      - uses: actions/upload-pages-artifact@v1
        with:
          path: doc/_site/
      - uses: actions/deploy-pages@v1
        id: deployment
